config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :contacts
  resources :questions do
    member do
      put "like", to: "questions#upvote"
      put "dislike", to: "questions#downvote"
    end
    resources :answers
  end

  devise_for :users

  get 'team', to: 'users#team', as: :team
  get 'profile/:id', to: 'users#profile', as: :profile
  
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end

  root to: 'questions#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)  
    user ||= User.new
    if user.admin?
        can :manage, :all
    else
        can :update, Question, user_id: user.id
        can :destroy, Question, user_id: user.id
        
        can :read, Question
        can :create, Question

        can :destroy, Answer, user_id: user.id
        can :read, Answer
        can :create, Answer

        can :destroy, Contact, user_id: user.id
        can :read, Contact
        can :create, Contact
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates_presence_of :body, allow_blank: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  validates_presence_of :message
end

app/models/question.rb
class Question < ApplicationRecord

  acts_as_votable
  
  belongs_to :user
  has_many :answers
  validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord

  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  def account_active
    locked_at.nil?
  end

  def active_for_authentication?
    super && account_active?
  end

  def inactive_message
    account_active? ? super: :locked
  end


  # RegExp To Allow Only Siswa Email For User Authentication
  validates :email, format: {
    with: /\b[A-Z0-9._%a-z\-]+@(siswa.upsi.edu)\.my\z/,
    message: "Must be a siswa account"
  }

  has_many :questions
  has_many :answers
  has_many :contacts
  has_many :bugs
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	
	load_and_authorize_resource

	before_action :set_answer
	before_action :authenticate_user!, only:[:create, :destroy]
	
	def create
		@answer = @question.answers.new(answer_params)
		@answer.user = current_user
		@answer.save
		redirect_to @question
	end

	def destroy
		@answer = @question.answers.find(params[:id])
		@answer_id = @answer.id
		@answer.destroy
	end

	private
	def answer_params
		params.require(:answer).permit(:body, :question_id)
	end
	def set_answer
		@question = Question.find(params[:question_id])
   end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   before_action :configure_permitted_parameters, if: :devise_controller?

   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
     devise_parameter_sanitizer.permit(:account_update, keys: [
         :name,
         :password,
         :password_confirmation,
         :address,
         :contact_number,
         :fb_link,
         :ig_link,
         :twitter_link,
         :in_link,
         :profile_pic
      ])
   end
 end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  load_and_authorize_resource
  
  before_action :set_contact, only: [ :destroy]
  before_action :authenticate_user!

  def index
    @contacts = Contact.all
  end
  
  def new
    @contact = current_user.contacts.build
  end

  def create
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_url, notice: 'Message was successfully sent.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:message, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
 
  load_and_authorize_resource
  skip_authorize_resource :only => [:upvote, :downvote]

  before_action :set_question, only: [:show, :edit, :update, :destroy,:upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @questions = Question.all.order('created_at DESC').paginate(page: params[:page], per_page: 4)
    @users = User.all.last(5)
  end

  def show
    @answer = Answer.new
    @answers = @question.answers.order('created_at DESC')
  end

  def new
    @question = current_user.questions.build
  end

  def edit
  end

  def create
    @question = current_user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote 
    @question.upvote_by current_user
    redirect_back fallback_location: root_path
  end 

  def downvote
    @question.downvote_by current_user
    redirect_back fallback_location: root_path
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :image_link, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!

  def team
  	@users = User.all.order('created_at ASC')
  end

  def profile
    @user = User.find(params[:id])
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<div id="answer-<%= answer.id %>">
   <div class="text-left">
      <% if !answer.user.name.blank? %>
         <strong>
         <%= link_to answer.user.name, profile_path(answer.user)  %>
         </strong>
      <% else %>
      <strong>
         <%= link_to answer.user.email, profile_path(answer.user) %>
         </strong>
      <% end %>

      <% if user_signed_in? %>
         <% if current_user && current_user == answer.user || current_user.admin? %>
            <%= link_to "Delete", question_answer_path(@question, answer), method: :delete, remote: true,:class=>"btn btn-sm btn-danger"%>
         <% end %>
      <% end %>
      <br>
      <span class="time"><%= time_ago_in_words(answer.created_at) %> ago</span>
      <p class="text-justify"><%= answer.body.html_safe %></p>
   </div>
</div>

app/views/answers/create.js.erb
#('#answer_pane').prepend("<%= j render @answer %>");
#('#answer_body').val(' ');

app/views/answers/destroy.js.erb
$('#answer-<%= @answer_id %>').html('');

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :message, label: false, input_html:{:rows=> 6}, placeholder: "Submit bug /  message..."%>
    <%= f.association :user, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit", :class=>"btn btn-light" %>
    <%= link_to "Back", contacts_path, :class=>"btn btn-light"%>
  </div>
<% end %>

app/views/contacts/index.html.erb
<% provide(:page_title, 'Browse Contact Logs') %>
<% if user_signed_in? %>
  <%= render 'shared/navbar_user' %>
<% else %>
  <%= render 'shared/navbar_public' %>
<% end %>
<% if current_user && current_user.admin? %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <p>All Contacts Log</p>
        <% @contacts.each do |contact| %>
          <div class="card mb-2" style="width: 100%;">
            <div class="card-header">
              <div class="float-right">
                <%= link_to contact, method: :delete,data: { confirm: 'Are you sure?' } do %>
                  <button class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                <% end %>
              </div>
              <%= contact.created_at.strftime("%B, %d, %Y")%> by
              <% if !contact.user.name.blank? %>
                <%= contact.user.name %>
              <% else %>
                <%= contact.user.email %>
              <% end %>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><%= contact.message%></li>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
<% if !current_user.contacts.blank? %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-12">
      <%= link_to "Contact", new_contact_path, :class=>"btn btn-info"%>
        <p>Your Contacts Log</p>
        <% current_user.contacts.each do |contact| %>
          <div class="card mb-2" style="width: 100%;">
            <div class="card-header">
              <div class="float-right">
                <%= link_to contact, method: :delete,data: { confirm: 'Are you sure?' } do %>
                  <button class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                <% end %>
              </div>
              <%= contact.created_at.strftime("%B, %d, %Y")%>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><%= contact.message%></li>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<% else %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <div class="alert alert-info" role="alert">
          Sorry we couldn't find any contact record!
      </div>
        <%= link_to "Go, contact if necessary", new_contact_path, :class=>"btn btn-info"%>
      </div>
    </div>
  </div>
<% end %>

<% end %>

app/views/contacts/new.html.erb
<% provide(:page_title, 'Contact Admin') %>
<% if user_signed_in? %>
  <%= render 'shared/navbar_user' %>
<% else %>
  <%= render 'shared/navbar_public' %>
<% end %>
<div class="container">
   <div class="row justify-content-center" style="margin-top: 10vh">
      <div class="col-lg-12">
         <div class="card bg-info">
            <div class="card-body">
            <h1 class="mb-3">Contact Admin</h1>
               <%= render 'form', contact: @contact %>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum | <%= yield(:page_title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag("origami.png") %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  </head>
  <body>
    <%= render 'shared/alert' %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :image_link, label: 'Image Link (Optional)' %>
    <%= f.association :user, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class=>"btn btn-primary" %>
    <%= link_to "Back", questions_path, :class=>"btn btn-info" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<% provide(:page_title, "Edit >#{@question.title }") %>
<% if user_signed_in? %>
  <%= render 'shared/navbar_user' %>
<% else %>
  <%= render 'shared/navbar_public' %>
<% end %>
<div class="container">
   <div class="row justify-content-center" style="margin-top: 10vh">
      <div class="col-lg-10">
         <div class="card">
            <div class="card-body">
               <h1>Edit Question</h1>
               <%= render 'form', question: @question %>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/questions/index.html.erb
<% provide(:page_title, 'Browse All Questions') %>
<% if user_signed_in? %>
  <%= render 'shared/navbar_user' %>
<% else %>
  <%= render 'shared/navbar_public' %>
<% end %>
<div class="container">
  <div class="row justify-content-center mt-4">
    <div class="col-lg-3">
    <span class="text-muted">STATS</span>
      <ul class="list-group shadow mb-4">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Total Members
          <span class="badge bg-primary rounded-pill">
            <%= User.all.count %>
          </span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Totals Questions Asked
          <span class="badge bg-primary rounded-pill"><%= Question.all.count %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Total Answers
          <span class="badge bg-primary rounded-pill">1</span>
        </li>
      </ul>
      <span class="text-muted">NEW USERS</span>
      <ul class="list-group shadow mb-2">
        <% @users.each do |user| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <%= user.email %>
          </li>
        <% end %>
      </ul>

      <% if user_signed_in? %>
        <% if current_user && current_user.admin? %>
          <%= link_to "Dashboard", rails_admin_path, :class=>"btn btn-info mt-2 btn-block"%>
        <% end %>
      <% end %>
      
    </div>
    <div class="col-lg-9">
    <%= link_to new_question_path do %>
      <button class="btn btn-success mb-2 shadow">
        <i class="fas fa-location-arrow"></i> Ask a question
      </button>
    <% end %>
    <% @questions.each do |question| %>
      <div class="card shadow mb-2">
        <div class="card-body">

        <% if user_signed_in? %>
					<% if current_user && current_user == question.user || current_user.admin? %>
              <div class="float-right">
                <% if can? :update, question %>
                    <%= link_to edit_question_path(question) do %>
                      <button class="btn btn-info">
                        <i class="fas fa-pencil-alt"></i>
                      </button>
                    <% end %>
                  <% end %>

                <% if can? :destroy, question %>
                  <%= link_to question, method: :delete,data: { confirm: 'Are you sure?' } do %>
                    <button class="btn btn-danger">
                      <i class="fas fa-minus-circle"></i>
                    </button>
                  <% end %>
                <% end %>
              </div>
          <% end %>
        <% end %>
          
          <p class="card-text lead"><strong><%= question.title %></strong></p>
          <small class="text-muted">Asked by <span class="text-info">
          <% if !question.user.name.blank? %>
            <%= link_to question.user.name, profile_path(question.user) %>
          <% else %>
            <%= link_to question.user.email, profile_path(question.user) %>
          <% end %>
          </span> at <%= question.created_at.strftime("%B, %d, %Y")%></small>
          <br>
          <span class="text-muted">
            <div class="badge badge-info"><i class="far fa-thumbs-up"></i> <%= question.get_upvotes.size %></div>
            <div class="badge badge-info"><i class="far fa-thumbs-down"></i> <%= question.get_downvotes.size %></div>
          </span>
          <%= link_to question do %>
            <button class="btn btn-primary btn-block mt-1">
            <i class="fas fa-arrow-alt-circle-right"></i>
            </button>
          <% end %>
        </div>
      </div>
    <% end %>
    <nav aria-label="Page navigation example" style="margin-top: 15px">
      <ul class="pagination pg-blue justify-content-center">
                <%= will_paginate(@questions,
                :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer,
                inner_window: 1,
                outer_window: 0,
                class: 'text-center') %>
      </ul>
    </nav>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<% provide(:page_title, 'Ask A Question') %>
<% if user_signed_in? %>
  <%= render 'shared/navbar_user' %>
<% else %>
  <%= render 'shared/navbar_public' %>
<% end %>
<div class="container">
   <div class="row justify-content-center" style="margin-top: 10vh">
      <div class="col-lg-10">
         <div class="card">
            <div class="card-body">
               <h1>Ask A New Question</h1>
               <%= render 'form', question: @question %>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/questions/show.html.erb
<% provide(:page_title, "#{@question.title}") %>
<% if user_signed_in? %>
  <%= render 'shared/navbar_user' %>
<% else %>
  <%= render 'shared/navbar_public' %>
<% end %>
<div class="container-fluid">
<div class="row justify-content-center">
  <div class="col-lg-11 mb-2">
    <div class="float-left">
      <%= link_to questions_path do %>
        <button class="btn btn-secondary">
          <i class="fas fa-chevron-circle-left"></i>
        </button>
      <% end %>

      <%= link_to new_question_path do %>
        <button class="btn btn-secondary">
          <i class="fas fa-chevron-circle-right"></i>
        </button>
      <% end %>
    </div>

    <% if user_signed_in? %>
					<% if current_user && current_user == @question.user || current_user.admin? %>
              <div class="float-right">
                <% if can? :update, @question %>
                  <%= link_to 'Edit', edit_question_path(@question),:class=>"btn btn-info" %>
                <% end %>

                <% if can? :destroy, @question %>
                  <%= link_to 'Delete', question_path, method: :delete, data:{confirm: 'Are you sure?'},:class=>"btn btn-danger" %>
                <% end %>
              </div>
          <% end %>
      <% end %>
  </div>
  
</div>
  <div class="row justify-content-center">
    <div class="col-lg-11">
      <div class="card shadow">
        <div class="card-body">
          <p class="lead text-center" style="margin-bottom: 0px">
            <strong><%= @question.title %></strong>
          </p>

          <% if @question.image_link %>
            <div class="text-center">
              <%= image_tag(@question.image_link, :class=>"img-fluid rounded shadow mt-4", :size=>"520x650")%>
            </div>
          <% end %>

          <p class="text-center text-muted text-italic mt-3">Asked <%=time_ago_in_words(@question.created_at) %> ago</p>
          <% if user_signed_in? %>
            <% unless current_user && current_user == @question.user %>
              <div class="text-center">
                <%= link_to like_question_path(@question), method: :put do %>
                  <button class="btn btn-primary btn-sm">
                    <i class="far fa-thumbs-up"></i> <%= @question.get_upvotes.size %>
                  </button>
                <% end %>

                <%= link_to dislike_question_path(@question), method: :put do %>
                  <button class="btn btn-primary btn-sm">
                    <i class="far fa-thumbs-down"></i> <%= @question.get_downvotes.size %>
                  </button>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @question.answers.count > 0 %>
  <div class="container-fluid mt-2">
    <div class="row justify-content-center">
      <div class="col-lg-11">
        <div class="card shadow">
          <div class="card-body">
            <div class="question-answers">
              <% @answers.each do |answer| %>
                <div id="answer_pane">
                  <%= render 'answers/answer', answer: answer %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="container-fluid mt-2">
    <div class="row justify-content-center">
      <div class="col-lg-11">
        <div class="card shadow">
          <div class="card-body">
            <p>No answer found for this question !</p>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% if user_signed_in? %>
<div class="container-fluid mt-2 mb-3">
  <div class="row justify-content-center">
    <div class="col-lg-11">
          <%= form_for [@question, @answer] do |f| %>
					<%= f.text_area :body,:class=>"form-control",placeholder:'Answer',rows:5  %>
					<%= f.submit "Answer",:class=>"btn btn-info mt-2" %>
          <%= link_to "Back", root_path, :class=>"btn btn-primary mt-2"%>
				<% end %>
    </div>
  </div>
</div>
<% else %>
<div class="container-fluid mt-2 mb-3">
  <div class="row justify-content-center">
    <div class="col-lg-11">
      <p class="lead">Please
        <strong><%= link_to "Login", new_user_session_path, :class=>"link-cyan"%></strong>
       to submit your answer</p>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_alert.html.erb
<% if notice %>
    <div id="notice_wrapper">
        <p class="notice">
            <%= notice %>
        </p>
    </div>
<% elsif alert %>
    <div id="notice_wrapper">
        <p class="alert">
            <%= alert %>
        </p>
    </div>
<% end %>

app/views/shared/_navbar_public.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-info border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">
    <%= image_tag('origami.png', :size=>"26x26", :class=>"img-fluid -mt-6")%>
    <strong>
      <%= link_to "UPSI Forum", root_path, :class=>"navbar-brand" %>  
    </strong>
  </h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <%= link_to "Home", root_path, :class=>"p-2 text-dark" %>
    <% if current_user && current_user.admin? %>
      <%= link_to "Community", team_path, :class=>"p-2 text-dark" %>
    <% end %>
    <%= link_to "Contact", contacts_path, :class=>"p-2 text-dark" %>
  </nav>
    <%= link_to "Login", new_user_session_path, :class=>"btn btn-light" %>
  <span class="px-1"></span>
  <%= link_to "Sign Up", new_user_registration_path, :class=>"btn btn-light" %>
</div>

app/views/shared/_navbar_user.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-info border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">
    <%= image_tag('origami.png', :size=>"26x26", :class=>"img-fluid -mt-6")%>
    <strong>
      <%= link_to "UPSI Forum", root_path, :class=>"navbar-brand" %>  
    </strong>
  </h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <%= link_to "Home", root_path, :class=>"p-2 text-dark" %>

    <% if current_user && current_user.admin? %>
      <%= link_to "Community", team_path, :class=>"p-2 text-dark" %>
    <% end %>

    <%= link_to "Contact", contacts_path, :class=>"p-2 text-dark" %>
    <span class="px-2"></span>
    <%= link_to edit_user_registration_path,:class=>"p-2 text-dark" do %>
      <i class="far fa-user"></i>
      Account Settings
    <% end %>

    <%= link_to destroy_user_session_path, method: :delete,:class=>"p-2 text-dark" do %>
      <i class="fas fa-sign-out-alt"></i>
      Log Out
      (
        <% if !current_user.name.blank? %>
            <%= current_user.name %>
         <% else %>
            <%= current_user.email %>
         <% end %>
      )
    <% end %>
  </nav>
</div>

app/views/users/team.html.erb
<% provide(:page_title, "Community") %>

<% if user_signed_in? %>
  <%= render 'shared/navbar_user' %>
<% else %>
  <%= render 'shared/navbar_public' %>
<% end %>
<div class="container">
   <div class="row justify-content-center" style="margin-top: 15vh">
      <div class="table-responsive">
         <table class="table">
            <thead>
               <tr>
               <th scope="col">Image</th>
               <th scope="col">Name</th>
               <th scope="col">Email</th>
               <th scope="col">Role</th>
               </tr>
            </thead>
            <tbody>
               <% @users.each do |user| %>
               <tr>
                  <td>
                     <% if !user.profile_pic.blank? %>
                        <%= link_to image_tag(user.profile_pic, :size=>"36x36",:class=>"rounded-circle"),profile_path(user) %>
                     <% else %>
                        <%= link_to image_tag('avatar.png', :size=>"36x36", :class=>"rounded-circle"), profile_path(user) %>
                     <% end %>
                  </td>

                  <td>
                     <% if !user.name.blank? %>
                        <%= link_to user.name, profile_path(user) %>
                     <% else %>
                        No Name Set
                     <% end %>
                  </td>

                  <td><%= link_to user.email, profile_path(user) %></td>

                  <td>
                     <% if user.admin? %>
                        <span class="text-info">Admin</span>
                     <% else %>
                        User
                     <% end %>
                  </td>
               </tr>
               <% end %>
            </tbody>
         </table>
      </div>
      
   </div>
   <%= link_to "Back", root_path, :class=>"btn btn-info -ml-2" %>
</div>